#!/usr/bin/env node
// Regenerates the ICANN TLD list the extension uses to tell "this ending exists
// on the real internet" from "this ending only exists in Moshpit".
//
//   node scripts/update-tlds.mjs
//
// Source of truth is IANA's own list. It changes rarely (a handful of new
// endings a year, and the odd retirement), so this is a manual chore rather
// than a build step — a network fetch in the build would make a release depend
// on data.iana.org being up.
//
// tlds.test.js asserts the generated file still parses and still holds the
// endings we depend on; it deliberately does NOT re-fetch, so the suite stays
// offline and deterministic.
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const SOURCE = 'https://data.iana.org/TLD/tlds-alpha-by-domain.txt';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'apps/desktop/extensions/ai-sidebar/tld-data.js');

const res = await fetch(SOURCE);
if (!res.ok) {
  console.error(`fetch ${SOURCE} failed: ${res.status}`);
  process.exit(1);
}
const text = await res.text();

// The first line is a comment carrying IANA's own version stamp. Keep it: it is
// how you tell a stale list from a current one without diffing 1400 strings.
const [header] = text.split('\n');
const version = /Version (\d+)/.exec(header)?.[1] ?? 'unknown';

const tlds = text
  .split('\n')
  .map((l) => l.trim().toLowerCase())
  .filter((l) => l && !l.startsWith('#'))
  .sort();

if (tlds.length < 1000) {
  console.error(`refusing to write ${tlds.length} TLDs — that is not the real list`);
  process.exit(1);
}

const body = `// GENERATED by scripts/update-tlds.mjs — do not edit by hand.
// IANA tlds-alpha-by-domain.txt, version ${version}.
//
// Every ending that exists on the real internet. Used to decide whether clearnet
// could ever legitimately answer for a hostname; see tlds.js for the policy.
export const IANA_TLD_VERSION = '${version}';

export const IANA_TLDS = ${JSON.stringify(tlds, null, 0).replace(/","/g, "','").replace(/^\["/, "[\n  '").replace(/"\]$/, "',\n]").replace(/','/g, "',\n  '")};
`;

writeFileSync(out, body);
console.log(`wrote ${tlds.length} TLDs (IANA version ${version}) to ${out.replace(root + '/', '')}`);
